[package]
name = "fedx"
version = "0.1.0"
edition = "2024"
publish = false

[dependencies]
axum = { version = "0.8" }
chrono = { version = "0.4.40", features = ["serde"] }
clap = { version = "4.5", features = ["derive", "env"] }
indoc = "2"
rusqlite = { version = "0.34.0", features = ["bundled", "chrono"] }
serde = { version = "1.0", features = ["derive"] }
tokio = { version = "1.44", features = ["rt-multi-thread", "macros"] }
tracing = "0.1"
tracing-subscriber = "0.3"
