[package]
name = "fedx"
version = "0.1.0"
edition = "2024"
publish = false

[lib]
crate-type = ["cdylib"]

[dependencies]
chrono = { version = "0.4.40", features = ["serde"] }
serde = { version = "1.0", features = ["derive"] }
sqlx-d1 = { version = "0.1", features = ["macros", "chrono"] }
worker = { version = "0.5", features = ["d1"] }
