app = 'fedx'
primary_region = 'ams'

[experimental]
  cmd = ['serve']

[build]
  dockerfile = 'Dockerfile'

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'off'
  auto_start_machines = false
  min_machines_running = 1

  [http_service.concurrency]
    type = 'connections'
    hard_limit = 100
    soft_limit = 10

  [[http_service.checks]]
    interval = '30s'
    timeout = '10s'
    grace_period = '15s'
    method = 'GET'
    path = '/'

[[restart]]
  policy = 'on-failure'
  retries = 2
  processes = ['app']

[[vm]]
  size = 'shared-cpu-1x'
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
