name: ci
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/bin/
            ~/.cargo/registry/index/
            ~/.cargo/registry/cache/
            ~/.cargo/git/db/
            target/
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
      - run: sudo apt install -y just
      - run: just release
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy public/ --config="../fly.toml" --remote-only
        if: github.event_name == 'push'
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
