name: ci
on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:
jobs:
  deploy:
    runs-on: ubuntu-latest
    concurrency: deploy-group
    steps:
      - uses: actions/checkout@v4
      - uses: superfly/flyctl-actions/setup-flyctl@master
      - run: flyctl deploy --remote-only
        if: github.event_name == 'push'
        env:
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
